CREATE SCHEMA production;
CREATE TABLE production.production_order(installation_id uuid NOT NULL,authority_scope uuid NOT NULL,customer_id uuid NOT NULL,order_id uuid NOT NULL,sales_order_id uuid NOT NULL,item_id uuid NOT NULL,record jsonb NOT NULL,state text NOT NULL CHECK(state IN('DRAFT','PLANNED','RELEASED','IN_PROGRESS','PARTIALLY_COMPLETED','COMPLETED','CLOSED')),PRIMARY KEY(installation_id,authority_scope,order_id),CHECK(record->>'id'=order_id::text AND record->>'customerId'=customer_id::text AND record->>'salesOrderId'=sales_order_id::text AND record->>'itemId'=item_id::text AND record->>'state'=state));
CREATE TABLE production.operation(installation_id uuid NOT NULL,authority_scope uuid NOT NULL,customer_id uuid NOT NULL,operation_id uuid NOT NULL,order_id uuid NOT NULL,record jsonb NOT NULL,state text NOT NULL CHECK(state IN('PLANNED','IN_PROGRESS','COMPLETED')),PRIMARY KEY(installation_id,authority_scope,operation_id),FOREIGN KEY(installation_id,authority_scope,order_id) REFERENCES production.production_order,CHECK(record->>'id'=operation_id::text AND record->>'productionOrderId'=order_id::text AND record->>'state'=state));
CREATE TABLE production.allocation(installation_id uuid NOT NULL,authority_scope uuid NOT NULL,customer_id uuid NOT NULL,allocation_id uuid NOT NULL,order_id uuid NOT NULL,record jsonb NOT NULL,state text NOT NULL CHECK(state IN('PLANNED','ASSIGNED','ISSUED','RELEASED')),PRIMARY KEY(installation_id,authority_scope,allocation_id),FOREIGN KEY(installation_id,authority_scope,order_id) REFERENCES production.production_order,CHECK(record->>'id'=allocation_id::text AND record->>'productionOrderId'=order_id::text AND record->>'state'=state));
CREATE TABLE production.source_fact(installation_id uuid NOT NULL,authority_scope uuid NOT NULL,customer_id uuid NOT NULL,fact_id uuid NOT NULL,order_id uuid NOT NULL,operation_id uuid NOT NULL,kind text NOT NULL CHECK(kind IN('CONSUMPTION','OUTPUT','RESIDUAL','SCRAP','FINALIZED','ENTRY','REFERRAL','DECLARATION')),data jsonb NOT NULL,issuer text NOT NULL,subject text NOT NULL,command_key text NOT NULL,actor_role text NOT NULL CHECK(actor_role IN('ACT-PLAN','ACT-OP')),occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(installation_id,authority_scope,fact_id),FOREIGN KEY(installation_id,authority_scope,order_id) REFERENCES production.production_order,FOREIGN KEY(installation_id,authority_scope,operation_id) REFERENCES production.operation,CHECK(jsonb_typeof(data)='object'));
CREATE INDEX source_fact_order ON production.source_fact(installation_id,authority_scope,customer_id,order_id);
CREATE FUNCTION production.source_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'Production source facts are immutable' USING ERRCODE='23514'; END IF;
 IF NOT EXISTS(SELECT 1 FROM production.operation o WHERE o.installation_id=NEW.installation_id AND o.authority_scope=NEW.authority_scope AND o.operation_id=NEW.operation_id AND o.order_id=NEW.order_id AND o.customer_id=NEW.customer_id AND (o.state='IN_PROGRESS' OR (NEW.kind IN('ENTRY','REFERRAL','DECLARATION') AND o.state='PLANNED') OR (NEW.kind='REFERRAL' AND o.state='COMPLETED'))) THEN RAISE EXCEPTION 'Source fact requires matching operation' USING ERRCODE='23514'; END IF;
 NEW.occurred_at:=clock_timestamp();RETURN NEW;
END $$;
CREATE TRIGGER source_immutable BEFORE INSERT OR UPDATE OR DELETE ON production.source_fact FOR EACH ROW EXECUTE FUNCTION production.source_immutable();
CREATE FUNCTION production.lifecycle_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Production history cannot be deleted' USING ERRCODE='23514'; END IF;
 IF TG_OP='INSERT' THEN
  IF (TG_TABLE_NAME='production_order' AND NEW.state<>'DRAFT') OR (TG_TABLE_NAME IN('operation','allocation') AND NEW.state<>'PLANNED') THEN RAISE EXCEPTION 'Invalid initial production lifecycle state' USING ERRCODE='23514'; END IF;
  RETURN NEW;
 END IF;
 IF NEW.installation_id<>OLD.installation_id OR NEW.authority_scope<>OLD.authority_scope OR NEW.customer_id<>OLD.customer_id OR NEW.order_id<>OLD.order_id THEN RAISE EXCEPTION 'Production binding cannot change' USING ERRCODE='23514'; END IF;
 IF TG_TABLE_NAME='production_order' THEN
  IF OLD.state NOT IN('DRAFT','PLANNED') AND (NEW.record-'state') IS DISTINCT FROM (OLD.record-'state') THEN RAISE EXCEPTION 'Released route is immutable' USING ERRCODE='23514'; END IF;
  IF NOT((OLD.state='DRAFT' AND NEW.state='PLANNED')OR(OLD.state='PLANNED' AND NEW.state IN('PLANNED','RELEASED'))OR(OLD.state='RELEASED' AND NEW.state='IN_PROGRESS')OR(OLD.state IN('IN_PROGRESS','PARTIALLY_COMPLETED') AND NEW.state IN('PARTIALLY_COMPLETED','COMPLETED'))OR(OLD.state='COMPLETED' AND NEW.state='CLOSED')) THEN RAISE EXCEPTION 'Invalid production order transition' USING ERRCODE='23514'; END IF;
 ELSIF TG_TABLE_NAME='operation' THEN
  IF (NEW.record-'state') IS DISTINCT FROM (OLD.record-'state') OR NOT((OLD.state='PLANNED' AND NEW.state='IN_PROGRESS')OR(OLD.state='IN_PROGRESS' AND NEW.state='COMPLETED')) THEN RAISE EXCEPTION 'Invalid operation transition' USING ERRCODE='23514'; END IF;
 ELSE
  IF (NEW.record-ARRAY['state','unitId']) IS DISTINCT FROM (OLD.record-ARRAY['state','unitId']) OR (OLD.state<>'PLANNED' AND NEW.record->>'unitId' IS DISTINCT FROM OLD.record->>'unitId') OR NOT((OLD.state='PLANNED' AND NEW.state IN('ASSIGNED','RELEASED'))OR(OLD.state='ASSIGNED' AND NEW.state IN('ISSUED','RELEASED'))) THEN RAISE EXCEPTION 'Invalid allocation transition' USING ERRCODE='23514'; END IF;
 END IF; RETURN NEW;
END $$;
CREATE TRIGGER order_lifecycle BEFORE INSERT OR UPDATE OR DELETE ON production.production_order FOR EACH ROW EXECUTE FUNCTION production.lifecycle_guard();
CREATE TRIGGER operation_lifecycle BEFORE INSERT OR UPDATE OR DELETE ON production.operation FOR EACH ROW EXECUTE FUNCTION production.lifecycle_guard();
CREATE TRIGGER allocation_lifecycle BEFORE INSERT OR UPDATE OR DELETE ON production.allocation FOR EACH ROW EXECUTE FUNCTION production.lifecycle_guard();
CREATE TABLE production.route_snapshot(installation_id uuid NOT NULL,authority_scope uuid NOT NULL,order_id uuid NOT NULL,version integer NOT NULL CHECK(version>0),route jsonb NOT NULL CHECK(jsonb_typeof(route)='array'),PRIMARY KEY(installation_id,authority_scope,order_id,version),FOREIGN KEY(installation_id,authority_scope,order_id) REFERENCES production.production_order);
CREATE FUNCTION production.route_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Released and historic routes cannot be mutated' USING ERRCODE='23514'; END $$;
CREATE TRIGGER route_immutable BEFORE UPDATE OR DELETE ON production.route_snapshot FOR EACH ROW EXECUTE FUNCTION production.route_immutable();
ALTER TABLE inventory.production_origin ADD CONSTRAINT production_origin_source FOREIGN KEY(installation_id,authority_scope,source_fact_id) REFERENCES production.source_fact(installation_id,authority_scope,fact_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE production.production_order ADD CONSTRAINT production_order_record_required CHECK(jsonb_typeof(record)='object' AND record ?& ARRAY['id','customerId','salesOrderId','itemId','state','routeVersion','route'] AND record->>'id' IS NOT NULL AND record->>'customerId' IS NOT NULL AND record->>'salesOrderId' IS NOT NULL AND record->>'itemId' IS NOT NULL AND record->>'state' IS NOT NULL AND jsonb_typeof(record->'route')='array' AND jsonb_typeof(record->'routeVersion')='number');
ALTER TABLE production.operation ADD CONSTRAINT operation_record_required CHECK(jsonb_typeof(record)='object' AND record ?& ARRAY['id','productionOrderId','state','index','station'] AND record->>'id' IS NOT NULL AND record->>'productionOrderId' IS NOT NULL AND record->>'state' IS NOT NULL AND jsonb_typeof(record->'index')='number' AND jsonb_typeof(record->'station')='string');
ALTER TABLE production.allocation ADD CONSTRAINT allocation_record_required CHECK(jsonb_typeof(record)='object' AND record ?& ARRAY['id','productionOrderId','state','kg'] AND record->>'id' IS NOT NULL AND record->>'productionOrderId' IS NOT NULL AND record->>'state' IS NOT NULL AND jsonb_typeof(record->'kg')='string' AND (record->>'kg')::numeric>0);
ALTER TABLE production.production_order ADD UNIQUE(installation_id,authority_scope,order_id,customer_id);
ALTER TABLE production.operation ADD UNIQUE(installation_id,authority_scope,operation_id,order_id,customer_id);
ALTER TABLE production.operation ADD FOREIGN KEY(installation_id,authority_scope,order_id,customer_id) REFERENCES production.production_order(installation_id,authority_scope,order_id,customer_id);
ALTER TABLE production.allocation ADD FOREIGN KEY(installation_id,authority_scope,order_id,customer_id) REFERENCES production.production_order(installation_id,authority_scope,order_id,customer_id);
ALTER TABLE production.source_fact ADD FOREIGN KEY(installation_id,authority_scope,operation_id,order_id,customer_id) REFERENCES production.operation(installation_id,authority_scope,operation_id,order_id,customer_id);
CREATE TABLE production.product_batch(installation_id uuid NOT NULL,authority_scope uuid NOT NULL,customer_id uuid NOT NULL,batch_id uuid NOT NULL,order_id uuid NOT NULL,operation_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(installation_id,authority_scope,batch_id),UNIQUE(installation_id,authority_scope,batch_id,operation_id,order_id,customer_id),FOREIGN KEY(installation_id,authority_scope,operation_id,order_id,customer_id) REFERENCES production.operation(installation_id,authority_scope,operation_id,order_id,customer_id));
CREATE TRIGGER batch_immutable BEFORE UPDATE OR DELETE ON production.product_batch FOR EACH ROW EXECUTE FUNCTION production.route_immutable();
ALTER TABLE inventory.production_origin ADD FOREIGN KEY(installation_id,authority_scope,product_batch_id,operation_id,production_order_id,customer_id) REFERENCES production.product_batch(installation_id,authority_scope,batch_id,operation_id,order_id,customer_id) DEFERRABLE INITIALLY DEFERRED;
